### ISSUE TITLE
"Are you sure want to leave chat?" not translatable

### ISSUE THREAD

**Issue by aloxe** [Mibew/mibew#215] opened 2017-11-01 14:14 UTC
### Environment
* Mibew Messenger version: 2.2.3
* OS: Linux
* Web server: apache

### Expected behavior

When leaving the chat clicking on [x], a confirmation window pops up and says "Are you sure want to leave chat?"

### Actual behavior

This sentence is not translated. It is not possible to translate from the `operator/translation` page in the backend.

### Steps to reproduce the behavior

Chose another language than English, start a chat, close the chat.

### Possible fix:
In Czech adding the following lines to `cs/translation.po` solves the problem.
`msgid "Are you sure want to leave chat?"`
`msgstr "Opravdu chcete ukončit chat?"`

**Comment by faf** [comment] 2017-11-01 20:50
> In Czech adding the following lines to cs/translation.po solves the problem.

So, the string is translatable after all, it's just unavailable in your localization interface, right?

**Comment by aloxe** [comment] 2017-11-01 21:04
yep and not available in the (czech) translation package.

**Comment by faf** [comment] 2017-11-01 22:23
> not available in the (czech) translation package

That's not a bug. The one and only source of all translatable strings is POT-file. Almost all localization packages are incomplete.

**Comment by faf** [comment] 2017-11-01 22:23
I'll take a look at possible causes of absence of the constant in the interface.

**Comment by aloxe** [comment] 2017-11-02 08:50
OK I added the line and this is taken into account. Where is the POT-file? I'd like to be sure we address every word but I can't find it in the distribution.

**Comment by faf** [comment] 2017-11-02 14:19
> Where is the POT-file?

The link to the latest version of POT file is available [on the official site](https://mibew.org/download2).

**Comment by faf** [comment] 2017-11-12 01:34
Back to the issue in question. Mibew Messenger has templates rendered on the server side and on the client side. Localization on the server side works fine: once Mibew Messenger encounters unknown string constant, it stores the constant in the database, so the string becomes available for translation in the interface. However there are no means to do the same thing on the client side. The cost of speed...

But actually the issue splits in two:

1. The lack of the client side functionality. Maybe someday it will be implemented. I've created the appropriate issue: #216.
2. The initial lack of the string constants in the interface, since Mibew Messenger needs to encounter a string before it will become available for altering by a user. And this behaviour is already fixed by de782c7fead6a360978f7ce199ac134a985ae472 for all new installations of Mibew Messenger, so the next release will comes along with the full initial English translation.

**Closed by faf** 2017-11-12 01:34 UTC
Labels: enhancement
