### ISSUE TITLE
Can't update to Mibew 2.2.3

### ISSUE THREAD

**Issue by tamatij** [Mibew/mibew#205] opened 2017-07-12 16:38 UTC
Hi there,

I am having an issue updating from Mibew 2.1.0 to 2.2.3. I have followed the update instructions as laid out in the in the ReadMe and on the Mibew documentation page. The issue occurs when I try to run the Update wizard as part of the last step for installation. I receive a HTTP Error 500 Internal server error and the following is written in the error log on the server:

`[####] [error] [client 10.9.250.80] PHP Fatal error:  Function name must be a string in /mibew/libs/classes/Mibew/Maintenance/Updater.php on line 139
`

We are running the following:

> Centos 6.9
> PHP 5.3.3 
> MYSQL 5.5.44
> Apache 2.2.15`

Any ideas?

**Comment by faf** [comment] 2017-07-13 00:17
We've [encountered this error before](https://github.com/Mibew/mibew/issues/140), but without any details.

> PHP 5.3.3

Most probably, that's the cause. We'll try to check it in the near future.

**Comment by faf** [comment] 2017-07-14 14:02
So, I can confirm that the cause is the version of PHP.

Since PHP 5.3 [is not supported](http://php.net/supported-versions.php) in any form for about 3 years, we won't fix this issue. Sorry about that.

It is possible to [upgrade PHP on CentOS 6.9](https://stackoverflow.com/questions/21502656/upgrading-php-on-centos-6-5-final). Hope it will help.

**Closed by faf** 2017-07-14 14:02 UTC
Labels: bug, wontfix

**Comment by or70** [comment] 2017-07-17 16:38
I have the same problem with PHP 5.3.17 on SLES 11.3. The required PHP version is 5.3.3 (https://github.com/Mibew/mibew and https://docs.mibew.org/installation-and-update.html). Maybe you should update the information.

**Comment by faf** [comment] 2017-07-17 16:52
You're right.

Actually I've just did it at Github. The docs will follow.
