### ISSUE TITLE
Error updating from version 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by leocampbel** [Mibew/mibew#140] opened 2015-09-13 21:27 UTC
removed all folders and installed the psata the new version, the IRE in the URL / update occurs the following error: Fatal error: Function name must be a string in /.../chat/libs/classes/Mibew/Maintenance/Updater.php on line 139
as consugo solve this, please!

**Comment by JustBlackBird** [comment] 2015-09-16 12:24
What version of PHP do you use?

**Comment by JustBlackBird** [comment] 2016-05-27 21:15
I cannot reproduce the problem and you did not provide any details of the problem. So I'm closing the issue as it cannot be reproduced.

**Closed by JustBlackBird** 2016-05-27 21:15 UTC
Labels: invalid
