### ISSUE TITLE
"Query failed: Table 'mibew.plugin' doesn't exist" when running install.php

### ISSUE THREAD

**Issue by jkmurrell** [Mibew/mibew#207] opened 2017-07-15 19:20 UTC
When running install at /install.php, this error appears. All database credentials are correct and have been double checked.

**Comment by dmcdaniel12** [comment] 2017-07-17 12:42
What version of Mibew are you trying to install?

**Comment by jkmurrell** [comment] 2017-07-17 17:06
V. 2.2.3

**Comment by faf** [comment] 2017-07-18 11:15
Looks like instead of running the front controller for the installation procedure the main front controller being used.

What about your web server (name, version, installed modules, etc.)?

**Comment by dj-calyx** [comment] 2017-07-28 03:09
Hi I have the same issue when attempting to install at /install

I've noticed that this might be due to the fact that /install redirects to /operator/login even though the instructions say to enter this into the browser. 

Typing in /install.php on the other hand brings up a 500 error which says the following in my apache error log:

_[Fri Jul 28 12:56:00.308811 2017] [:error] [pid 4983] [client 58.173.17.67:52890] PHP Fatal error:  Database was not initialized correctly in /var/www/html/mibew/libs/classes/Mibew/Database.php on line 120_

Any assistance with this would be greatly appreciated, thank you.



I'm running Apache 2.4.10 on Debian 8 with PHP 5.6.30.

**Apache Modules:**
core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cache_module (shared)
 cache_disk_module (shared)
 cgi_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_itk_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 unique_id_module (shared)

**PHP modules:**
bcmath
bz2
calendar
Core
ctype
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

**Comment by dj-calyx** [comment] 2017-07-31 23:54
Is there perhaps a different forum where I could get assistance with this as it is of critical importance?

**Comment by faf** [comment] 2017-08-14 14:18
@jkmurrell Still waiting to hear from you.

@dj-calyx 
1. It's not a forum. It's bugtracker. We're trying to catch and fix bugs here.
2. Are you sure that your issue is the same as of @jkmurrell ? Have you checked your database credentials and if so, how have you did this?
3. Have you allowed the use of `mod_rewrite` in `.htaccess`?

**Comment by faf** [comment] 2017-10-02 22:55
The issue will be closed due to inactivity in 2 weeks.

**Comment by faf** [comment] 2017-10-11 13:56
There is a topic at our forum related to the issue: https://mibew.org/forums/index.php/topic,192142.0.html

In order to figure out how to reproduce the problem, I'm duplicating my questions here:

Correct me if I'm wrong. To reproduce the issue one should:

1. Setup standard LAMP system (let it be Debian 8 with Apache 2.4.10, PHP 5.6.30, and multiple modules and PHP extensions as was described [here](https://github.com/Mibew/mibew/issues/207#issuecomment-318544858)).

2. Download our official distribution: [`https://mibew.org/download2`](https://mibew.org/download2)

3. Unpack the distribution at `/<server document root>/mibew/`

4. Prepare valid configuration for Mibew Messenger (i.e. `configs/config.yml`)

5. Visit `http://<server>/mibew/install`

Right? Is it a **full** list of steps to reproduce the issue **without any missed parts**?

**Comment by faf** [comment] 2017-10-27 22:15
So, I've finally try to reproduce the problem.

First of all, the [listed configuration](https://github.com/Mibew/mibew/issues/207#issuecomment-318544858) is not the default one. There were several default modules extra enabled, namely:

- `cache_module (shared)`
- `cache_disk_module (shared)`
- `cgi_module (shared)`
- `expires_module (shared)`
- `headers_module (shared)`
- `proxy_module (shared)`
- `proxy_http_module (shared)`
- `rewrite_module (shared)`
- `socache_shmcb_module (shared)`
- `ssl_module (shared)`
- `unique_id_module (shared)`

And one additional extra module installed, namely:

- `mpm_itk_module (shared)`

But that's not the case.

Second of all, in the [list of PHP modules](https://github.com/Mibew/mibew/issues/207#issuecomment-318544858) there are no required `curl` module. But that's not the case too.

Third of all, I've recreated the whole environment **known to me** by the messages from @dj-calyx (i.e. Debian 8.8.0, MySQL 5.5.58, PHP 5.6.30, etc.), but still were unable to reproduce the issue.

The only extra thing that I've done besided the steps listed in the `README.txt` were the changes in the configuration of Apache for the default site. I've enabled the possibility to use `mod_rewrite` directives in `.htaccess`. The fragment of the configuration is listed below (but it's pretty standard):

``` 
   <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
```

However, even without this I were able to install Mibew Messenger using the direct link: `http://<server>/mibew/install.php`.

So, at the moment I'm closing the issue. Anyone is free to reopen it, but only in case of additional information been provided.

**Closed by faf** 2017-10-27 22:15 UTC
Labels: invalid
