### ISSUE TITLE
running on a dedicated server

### ISSUE THREAD

**Issue by romadewir** [Mibew/mibew#130] opened 2015-07-28 21:14 UTC
I can't use localhost
I have to use an IP address in the connection settings for the database. But then during installation it can't connect to the database (already created). I'm 100% sure the information in config.yml is correct. Running it local was no problem.
![connection_error](https://cloud.githubusercontent.com/assets/13545409/8943965/fab11e28-357d-11e5-8b61-6b6f1f299f61.jpg)

I hope you have a solution for this.

**Comment by JustBlackBird** [comment] 2015-07-30 10:13
The problem does not related with Mibew. Something is wrong with your MySQL configuration. I've searched the Google for you and here is the first link I found: http://stackoverflow.com/questions/5376427/cant-connect-to-local-mysql-server-through-socket-var-mysql-mysql-sock-38

**Comment by JustBlackBird** [comment] 2016-01-25 15:01
I'm closing this because the problem is not related with Mibew itself.

**Closed by JustBlackBird** 2016-01-25 15:01 UTC
Labels: invalid
