### ISSUE TITLE
Error al Ingresar

### ISSUE THREAD

**Issue by jonasrrq** [Mibew/mibew#163] opened 2016-06-16 06:43 UTC
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator to inform of the time the error occurred and of anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Reviso el log y me arroja el siguiente error
2016-06-16 06:30:19 W3SVC10 S18259770 217.160.132.77 GET /mibew/index.php - 80 - 185.13.202.219 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/51.0.2704.84+Safari/537.36 MibewSessionID=9g4e7aoesdj6unvdhaniqjg5v0;+mibew_locale=es;+_ga=GA1.2.1762028240.1460570357 - cercasa.es 500 0 0 1763 510 3919
2016-06-16 06:38:24 W3SVC10 S18259770 217.160.132.77 GET /mibew/index.php - 80 - 185.13.202.219 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/51.0.2704.84+Safari/537.36 MibewSessionID=9g4e7aoesdj6unvdhaniqjg5v0;+mibew_locale=es;+_ga=GA1.2.1762028240.1460570357 - cercasa.es 500 0 0 1763 510 10246

**Comment by faf** [comment] 2016-06-16 14:32
Duplicate of issue #162

**Closed by faf** 2016-06-16 14:32 UTC
Labels: duplicate
