### ISSUE TITLE
Multiple 'Visitor closed chat window' messages

### ISSUE THREAD

**Issue by ollylh** [Mibew/mibew#154] opened 2016-04-29 20:41 UTC
I'm fairly new to Mibew, and I'm not much of a programmer/developer, so forgive the naivety before we begin.  :P

Yesterday I noticed an error with the system where there would be a message saying "Visitor closed chat window", which is normal at this stage, but then the message would repeat several times. This does not normally happen, and I would very much like it to stop happening! The message should only appear once, and then not again until a new messenger has joined and quit. This has been the way it has worked for me for years until yesterday, which is odd.

I've been trying to deduce the issue, and the only think I can think of is if the person on the other end is using our Mibew from a mobile device, the messages could be coming from them constantly closing and re-opening their web browser app. Do you think this could be the issue?

**Comment by JustBlackBird** [comment] 2016-05-27 21:10
Hi, sorry for the late answer, I just lost your issue.

Frankly, I cannot reproduce the problem, so any details will be more then useful. Don't you think the problem can be caused by continuous connects/disconnects of client?

Is there any info about what browser/platform uses the client and what did he/she saw in chat window?

Don't you think that it was a kind of crawler somehow opened chat window?

**Comment by ollylh** [comment] 2016-05-27 22:59
Hi, thanks for replying!

It seems the issue hasn't been repeated since the first few times, and therefore I am not able to gather more information. The only logical explanation I can think of is someone continuously opening and closing the browser during a conversation, and seeing as this hasn't become an issue for me, I'm comfortable with using that answer 👍 .

:)

**Comment by JustBlackBird** [comment] 2016-05-28 09:27
I have to close it now because we cannot reproduce it. I'll reopen it once some more details about the problem will be found.

**Closed by JustBlackBird** 2016-05-28 09:27 UTC
