### ISSUE TITLE
PHP7 compatability...

### ISSUE THREAD

**Issue by J-Fricke** [Mibew/mibew#175] opened 2016-09-22 00:40 UTC
The dependencies for the `justblackbird/handlebars.php-helpers` package are now out of date and cause fatal error in php7. I have not tested updating the version # yet, but making this ready for php7 might be as easy as updating that and the packages `xamin/handlebars.php` to greater versions in the composer.json file.

**Comment by J-Fricke** [comment] 2016-09-22 20:44
I believe this solves the issue #176

**Comment by faf** [comment] 2016-09-24 14:24
Thanks, @J-Fricke .

At the time we haven't tested Mibew with PHP7. Are you sure that this is the only compatibility issue?

**Comment by otarza** [comment] 2016-09-27 18:22
@faf I can confirm that this is the only issue I experienced while installing Mibew on php7, I have manually refactored `String` to `StringWrapper` in `justblackbird/handlebars.php-helpers` and it worked. 

Of course we need to update hadnlebars.php to version `0.10.3`.

**Comment by faf** [comment] 2016-10-03 11:25
Ok, great to hear that. Then we're waiting for complete PR. :)

**Comment by otarza** [comment] 2016-11-06 09:53
Guys, problem here is that https://github.com/JustBlackBird/handlebars.php-helpers already fixed this issue in their newer versions, but Mibew Messenger doesn't support newer version of this library. 

As a workaround solution I just created a patch for `justblackbird/handlebars.php-helpers` and added my patch to `composer.json` file, if you are happy with this solution you can use it, have a look at this gist: https://gist.github.com/otarza/68f946325dd077c501894f76c0bfa637

**Comment by J-Fricke** [comment] 2016-11-08 23:56
@otarza Have you tried the composer version updates and String namespace -> Text namespace change listed in #176 ?

**Comment by faf** [comment] 2016-11-18 11:12
Most probably, fixed by #176. If there will be no more bug reports, the issue will be closed in two weeks.

**Comment by JMCA2** [comment] 2016-12-14 13:59
It's been way over two weeks already, when will this be released on a new Mibew version? Thanks

**Comment by faf** [comment] 2016-12-15 12:47
ok, the issue is closed.

as about new version of Mibew Messenger, *maybe* we'll release it before the end of the year.

**Closed by faf** 2016-12-15 12:47 UTC
Labels: bug
